### ISSUE TITLE
Where can I get user profile data?

### ISSUE THREAD

**Issue by Sixy1204** [bigheiniu/X-COVID#3]
Hello,

I checked the google driver but didn't find user profiles data. 

Where can I get user profile data?

Thank you

**Comment by bigheiniu** [comment]
Hi,
Due to the Twitter data release policy, we can only release the Tweet ID and User ID for academic usage. 
When you hydrate the tweet id (id -> tweet text, user meta-information, and release date), it will return the user meta-information (user profile and user ID). 
You can check https://blog.twitter.com/developer/en_us/topics/tools/2021/enabling-the-future-of-academic-research-with-the-twitter-api.html for academic Twitter data hydrate.
